name: Deploy Portal to Google Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'portal/**'
      - '.github/workflows/railway-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: yamatovision-blue-lamp
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate Docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          cd portal
          docker build -t asia-northeast1-docker.pkg.dev/yamatovision-blue-lamp/appgenius/portal-backend:${{ github.sha }} .
          docker push asia-northeast1-docker.pkg.dev/yamatovision-blue-lamp/appgenius/portal-backend:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy appgenius-portal-backend \
            --image asia-northeast1-docker.pkg.dev/yamatovision-blue-lamp/appgenius/portal-backend:${{ github.sha }} \
            --platform managed \
            --region asia-northeast1 \
            --allow-unauthenticated \
            --port 5000 \
            --memory 1Gi \
            --set-env-vars="CORS_ORIGIN=https://geniemon.vercel.app,https://geniemon-yamatovisions-projects.vercel.app,https://geniemon-git-main-yamatovisions-projects.vercel.app,vscode-webview://*"